# Copyright [2025] [IBM]
# Licensed under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
# See the LICENSE file in the project root for license information.
# This file has been modified with the assistance of IBM Bob AI tool

from app.core.registry import service_registry
from app.services.data_protection_rules.models.create_rule import (
    CreateRuleRequest,
    CreateRuleResponse,
)
from app.core.settings import settings, ENV_MODE_SAAS
from app.services.data_protection_rules.utils.create_rule_util import (
    create_rule_from_payload,
    get_json_to_data_protect_rule,
)
from app.shared.logging.generate_context import auto_context
from app.shared.logging import LOGGER
from app.shared.exceptions.base import ExternalAPIError
from app.shared.utils.tool_helper_service import tool_helper_service
# Message templates for natural language rule creation
REFER_OBJECT_MESSAGE_TEMPLATE = (
    "To create a data protection rule, a referenced object in your request has some issues.\n"
    "**Reason:**\n {error_message}\n"
)

WRONG_RULE_FORMAT_MESSAGE_TEMPLATE = (
    "**User input**: {user_input}, \n"
    "Since your request couldn't be automatically converted into a valid data protection rule format, you'll need to define it more precisely. \n"
    "**Example Rule Patterns:** \n"
    "1. **Mask sensitive data:**  \n"
    "Mask the CreditCardNumber column in the customer_transactions table for all users except those in the Fraud Analysts user group.\n "
    "2. **Restrict access:** \n"
    "Deny access to any data assets classified as Personally Identifiable Information in the employee_db schema for users who are not members of the HR_Managers user group. \n"
    "3. **Filter data:**  \n"
    "Filter rows from the loan_applications table where the credit_score column is below 600 whenever the user belongs to the ExternalPartners group. \n"
    "\nPlease specify which type of rule you need and provide the exact details including:\n"
    "- Table/schema name. \n"
    "- Column name to protect. \n"
    "- User groups, User name or Tag to include/exclude. \n"
    "- Support governance artifacts: Data class, Business term, Classification. \n"
    "- Specific protection action (mask column, deny access, filter rows, obfuscate column, substitute column.)")

RULE_CREATION_DESCRIPTION = ("""Create a data protection rule from JSON string generated by client-side LLM.

⚠️ CRITICAL: This tool expects a JSON STRING, not natural language text!

CLIENT-SIDE LLM MUST use the prompt template below to convert natural language to JSON.

═══════════════════════════════════════════════════════════════════════════════
PROMPT TEMPLATE FOR CLIENT-SIDE LLM (Use this to generate JSON from natural language)
═══════════════════════════════════════════════════════════════════════════════

You are an expert data protection rule parser. Convert natural language into structured JSON rules following the exact API specification.

**STOP! READ THIS FIRST - ABSOLUTE PROHIBITIONS:**
These terms DO NOT EXIST and will cause IMMEDIATE FAILURE:
- $Column.Tag, $Column.Classification, $Asset.Classification, $govern.classification, $Data.Column

**CRITICAL CONSTRAINTS:**
1. Output ONLY valid JSON - no explanations, no markdown, no extra text
2. All terms MUST start with $ and be from VALID TERMS list
3. PREFIX RULES FOR VALUES:
   - $Asset.UserClassification, $Asset.InferredClassification, $Business.Term: values start with $ (e.g., ["$Personally Identifiable Information"])
   - $User.Name, $User.Role, $Asset.Owner: values start with # (e.g., ["#john.doe"])
   - $User.Group: values have NO prefix (e.g., ["HR_Managers"])
   - $Asset.Name, $Asset.Schema, $Asset.ColumnName, $Asset.Tags: values start with # (e.g., ["#customer_transactions"])

**AVAILABLE TERMS (ONLY THESE - NO OTHERS ALLOWED):**
⚠️ CRITICAL: You MUST use ONLY these exact terms. Any other term (like $Column.Tag, $Data.Column, etc.) is INVALID and will cause errors.

VALID TERMS:
- $Business.Term
- $Asset.UserClassification
- $Asset.InferredClassification
- $User.Name
- $User.Role
- $User.Group
- $Asset.Owner
- $Asset.Tags (plural - for tag-based conditions)
- $Asset.ColumnName (for column name matching)
- $Asset.Schema (for schema matching)
- $Asset.Name (for asset/table name matching)

INVALID TERMS (DO NOT USE - THESE WILL CAUSE ERRORS):
- $Column.Tag  DOES NOT EXIST
- $Column.Classification  DOES NOT EXIST
- $Asset.Classification  DOES NOT EXIST (use $Asset.UserClassification or $Asset.InferredClassification)
- $Data.Column  DOES NOT EXIST
- $Asset.Tag (singular)  DOES NOT EXIST (use $Asset.Tags plural)
- $govern.classification  DOES NOT EXIST
- Any term not in the VALID TERMS list above

IF YOU USE ANY INVALID TERM, THE RULE WILL FAIL!
THESE TERMS DO NOT EXIST IN THE API - DO NOT INVENT NEW TERMS!

**TRIGGER OPERATORS:**
- CONTAINS: ["$term", "CONTAINS", ["#value1", "#value2"]] or ["$term", "CONTAINS", ["$guid"]]
- LIKE: ["$term", "LIKE", "#abc"]

**TRIGGER LOGICAL OPERATORS:**
- AND: [condition1, "AND", condition2]
- OR: [condition1, "OR", condition2]
- NOT: ["NOT", condition]

**ALLOWED ACTIONS:**
- Transform (with subaction)
- Deny (simple)

**ALLOWED SUBACTIONS:**
redactColumns, redactDataClasses, redactTags, redactBusinessTerms, redactClassifications,
anonymizeColumns, anonymizeDataClasses, anonymizeTags, anonymizeBusinessTerms, anonymizeClassifications,
pseudonymizeColumns, pseudonymizeDataClasses, pseudonymizeTags, pseudonymizeBusinessTerms, pseudonymizeClassifications,
filter_include, filter_exclude, join_include, join_exclude

**TAG HANDLING RULES:**
CRITICAL: When user says "columns tagged X" or "anonymize columns tagged":
1. ✅ CORRECT subaction: "anonymizeTags" (NOT anonymizeColumns!)
2. ✅ CORRECT parameters: [{"name": "tag_names", "value": ["tag1", "tag2"]}]
3. ✅ CORRECT trigger for asset tags: "$Asset.Tags" with "CONTAINS" operator
4. ❌ NEVER use "anonymizeColumns" for tag-based rules
5. ❌ NEVER use "$Column.Tag" or "$govern.classification"
6. ❌ NEVER leave parameters empty []

🎯 EXACT PATTERN for "Anonymize columns tagged tag1 or tag2 in assets tagged tagasset":
{
  "action": {
    "name": "Transform",
    "subaction": {
      "name": "anonymizeTags",  ← NOT anonymizeColumns!
      "parameters": [{"name": "tag_names", "value": ["tag1", "tag2"]}]  ← NOT empty!
    }
  },
  "trigger": [["$Asset.Tags", "CONTAINS", ["#tagasset"]]]  ← Simple, not nested!
}

**ALLOWED PARAMETERS:**
column_names, dataclass_ids, tag_names, business_term_ids, classification_global_ids

**PARAMETER EXTRACTION RULES:**
- For column_names: Extract the actual column names mentioned in the user input (e.g., "salary", "CreditCardNumber")
- For table/asset names: Extract the actual table names mentioned (e.g., "customer_transactions", "employee_db")
- For group names: Extract the actual group names mentioned (e.g., "ExternalPartners", "HR_Managers")
- For schema names: Extract the actual schema names mentioned (e.g., "prod_finance", "employee_db")
- DO NOT use generic terms like $Data.Column in parameter values - always use the specific names from the input

**ALLOWED Predicate for filter_include and filter_exclude:**
- EQUALS
- LESS_THAN
- LESS_THAN_EQUALS
- GREATER_THAN
- GREATER_THAN_EQUALS

**EXAMPLES:**

Example #1 - TAG-BASED ANONYMIZATION:
Input: "Anonymize columns tagged tag1 or tag2 in assets tagged tagasset as draft"
Output:
{
  "action": {"name": "Transform", "subaction": {"name": "anonymizeTags", "parameters": [{"name": "tag_names", "value": ["tag1", "tag2"]}]}},
  "trigger": [["$Asset.Tags", "CONTAINS", ["#tagasset"]]],
  "name": "Anonymize columns tagged tag1 or tag2 in assets tagged tagasset",
  "description": "Anonymize columns tagged tag1 or tag2 in assets tagged tagasset",
  "governance_type_id": "Access",
  "state": "draft"
}

Example #2 - COLUMN MASKING:
Input: "Mask the CreditCardNumber column in the customer_transactions table for all users except those in the Fraud Analysts user group."
Output:
{
  "action": {"name": "Transform", "subaction": {"name": "redactColumns", "parameters": [{"name": "column_names", "value": ["CreditCardNumber"]}]}},
  "trigger": [["NOT", ["$User.Group", "CONTAINS", ["Fraud Analysts"]]], "AND", ["$Asset.Name", "CONTAINS", ["#customer_transactions"]]],
  "name": "Mask the CreditCardNumber column in the customer_transactions table",
  "description": "Mask the CreditCardNumber column in the customer_transactions table for all users except those in the Fraud Analysts user group.",
  "governance_type_id": "Access",
  "state": "active"
}

Example #3 - DENY WITH MULTIPLE CONDITIONS:
Input: "Deny access to any data assets classified as Personally Identifiable Information for business term contains address and data class is email and asset name like aaa"
Output:
{
  "action": {"name": "Deny"},
  "trigger": [["$Asset.UserClassification", "CONTAINS", ["$Personally Identifiable Information"]], "AND", ["$Business.Term", "CONTAINS", ["$address"]], "AND", ["$Asset.InferredClassification", "CONTAINS", ["$email"]], "AND", ["$Asset.Name", "LIKE", ["#aaa"]]],
  "name": "Deny access to any PII in catalog and asset combine rules",
  "description": "Deny access to any data assets classified as Personally Identifiable Information for catalog id is cc3333 and asset id is aa2222 and asset name like aaa.",
  "governance_type_id": "Access",
  "state": "active"
}

Example #4 - FILTER WITH PREDICATES:
Input: "Filter rows from the transactions table where transaction_amount > 10000 and region = 'APAC', but only for users in either the ExternalAuditors or ComplianceTeam groups and when the asset schema equals prod_finance."
Output:
{
  "action": {"name": "Transform", "subaction": {"name": "filter_include", "parameters": [{"name": "predicate", "value": [["$$transaction_amount", "GREATER_THAN", "#10000"], "AND", ["$$region", "EQUALS", "#'APAC'"]]}]}},
  "trigger": [["$Asset.Name", "CONTAINS", ["#transactions"]], "AND", ["$User.Group", "CONTAINS", ["ExternalAuditors", "ComplianceTeam"]], "AND", ["$Asset.Schema", "CONTAINS", ["#prod_finance"]]],
  "name": "Filter High-Value APAC Transactions for Auditors",
  "description": "Filter rows from the transactions table where transaction_amount > 10000 and region = 'APAC', but only for users in either the ExternalAuditors or ComplianceTeam groups and when the asset schema equals prod_finance.",
  "governance_type_id": "Access",
  "state": "active"
}

Example #5 - BUSINESS TERM ANONYMIZATION:
Input: "Substitute data for column with email business term when classification include any sensitive personal information or personally identification and column name like any aaa or bbb and asset name like ssn"
Output:
{
  "action": {"name": "Transform", "subaction": {"name": "anonymizeBusinessTerms", "parameters": [{"name": "business_term_ids", "value": ["email"]}]}},
  "trigger": [["$Asset.UserClassification", "CONTAINS", ["$sensitive personal information", "$personally identification"]], "AND", ["$Asset.ColumnName", "LIKE", ["#aaa", "#bbb"]], "AND", ["$Asset.Name", "LIKE", ["#ssn"]]],
  "name": "DSubstitute data for column with email business term when some rule match",
  "description": "Substitute data for column with email business term when classification include any sensitive personal information or personally identification and column name like any aaa or bbb and asset name like ssn",
  "governance_type_id": "Access",
  "state": "active"
}

Example #6 - DATA CLASS PSEUDONYMIZATION WITH OR/NOT:
Input: "Obfuscate all data class with Email and Account Number when asset owner is Yang or user name is Chen, or tag does not include tag1"
Output:
{
  "trigger": [["$Asset.Owner", "CONTAINS", ["#Yang"]], "OR", ["$User.Name", "CONTAINS", ["#Chen"]], "OR", ["NOT", ["$Asset.Tags", "CONTAINS", ["#tag1"]]]],
  "action": {"name": "Transform", "subaction": {"name": "pseudonymizeDataClasses", "parameters": [{"name": "dataclass_ids", "value": ["Email", "Account Number"]}]}},
  "name": "Obfuscate all data class with Email and Account Number when some rule match",
  "description": "Obfuscate all data class with Email and Account Number when asset owner is Yang or user name is Chen, or tag does not include tag1",
  "governance_type_id": "Access",
  "state": "active"
}

Example #7 - JOIN WITH REFERENCE ASSET:
Input: "Include rows from tables where the asset name contains 'COMMERCIAL_CLIENT', by joining with the COMMERCIAL_CLIENT reference asset from the AgentTest catalog. Only include rows where the source table's NAME column matches the reference table's EMAIL_ADDRESS column AND the reference table's COMMERCIAL_CLIENT column equals 'TRUE'"
Output:
{
  "trigger": ["$Asset.Name", "CONTAINS", ["#COMMERCIAL_CLIENT"]],
  "action": {"name": "Transform", "subaction": {"name": "join_include", "parameters": [{"name": "predicate", "value": [["$$source.NAME", "EQUALS", "$$references[0].EMAIL_ADDRESS"], "AND", ["$$references[0].COMMERCIAL_CLIENT", "EQUALS", "#'TRUE'"]]}, {"name": "references", "value": [{"catalog_id": "Default", "asset_id": "COMMERCIAL_CLIENT", "resource_key": "COMMERCIAL_CLIENT_resource_key"}]}]}},
  "name": "Include rows based on reference asset COMMERCIAL_CLIENT",
  "description": "Include rows from tables where the asset name contains 'COMMERCIAL_CLIENT', by joining with the COMMERCIAL_CLIENT reference asset from the AgentTest catalog. Only include rows where the source table's NAME column matches the reference table's EMAIL_ADDRESS column AND the reference table's COMMERCIAL_CLIENT column equals 'TRUE'",
  "governance_type_id": "Access",
  "state": "active"
}

**STEP-BY-STEP PARSING:**
1. Identify the ACTION: What should happen? (Transform/Deny/etc.)
2. Identify the SUBACTION: If Transform, what type? (anonymizeColumns, redactColumns, anonymizeTags, etc.)
   - If user says "columns tagged X" → use "anonymizeTags" with tag_names parameter
   - If user says "mask column Y" → use "redactColumns" with column_names parameter
3. Extract SPECIFIC VALUES: What column names, table names, group names, TAG NAMES are mentioned?
4. Build TRIGGER CONDITIONS: What conditions determine when this rule applies?
   - ONLY use terms from the VALID TERMS list above
   - For asset tag conditions: use "$Asset.Tags" (plural)
   - NEVER invent terms like "$Column.Tag"
5. Use EXACT VALUES in parameters, not generic terms
6. Use USER_INPUT and set in 'description' field
7. Generate a name from description and set in 'name' field
8. **VALIDATION CHECK**: Before outputting, verify ALL terms start with $ and are in the VALID TERMS list

**OUTPUT (JSON only):**

═══════════════════════════════════════════════════════════════════════════════
END OF PROMPT TEMPLATE
═══════════════════════════════════════════════════════════════════════════════

WORKFLOW (call this tool twice):

1. FIRST CALL - Preview Mode:
   - Call with preview_only=true (default)
   - Pass JSON string as rule_json
   - Tool returns formatted preview
   - SHOW PREVIEW TO USER
   - Ask: "Would you like to create this rule? (yes/no)"

2. SECOND CALL - Create Mode:
   - After user confirms "yes"
   - Call with preview_only=false and SAME JSON string
   - Tool creates rule and returns rule_id and url

DO NOT set preview_only=false without user confirmation.

Args:
    request: CreateRuleRequest with rule_json (JSON string) and preview_only flag

Returns:
    CreateRuleResponse with success status and message
""")

@service_registry.tool(
    name="create_data_protection_rule",
    description=RULE_CREATION_DESCRIPTION,
    tags={"create", "data_protection_rules", "json", "llm_integration"},
    meta={"version": "2.0", "service": "data_protection_rules"},
)
@auto_context
async def create_data_protection_rule(request: CreateRuleRequest) -> CreateRuleResponse:
    """Handle create data protection rule requests from JSON string."""
    
    if not request.rule_json:
        return CreateRuleResponse(
            success=False,
            message="Rule json string is required",
            error="Rule json string is required"
        )
    
    LOGGER.info(f"Create Data Protection Rule from text, input: {request.rule_json}, preview_only: {request.preview_only}")
    
    try:
        common_message = WRONG_RULE_FORMAT_MESSAGE_TEMPLATE.format(user_input=request.rule_json)
        
        # Extract structured parameters from natural language
        structured_params = await get_json_to_data_protect_rule(request.rule_json)
        
        if not structured_params.get("rule_json"):
            return CreateRuleResponse(
                success=False,
                message=common_message,
                error="Failed to parse rule description"
            )
        
        # Check for validation failures
        status = structured_params.get("status", "")
        if "failed" in status:
            LOGGER.warning(f"Validation failed for DPS rule create: {structured_params.get('message')}")
            message = REFER_OBJECT_MESSAGE_TEMPLATE.format(error_message=structured_params.get('message'))
            return CreateRuleResponse(
                success=False,
                message=message,
                error=structured_params.get('message')
            )
        
        if "error" in status:
            LOGGER.warning(f"Error in DPS rule create: {structured_params.get('message')}")
            return CreateRuleResponse(
                success=False,
                message=structured_params.get('message', 'Unknown error occurred'),
                error=structured_params.get('message')
            )
        
        # Create summary for preview
        rule_json = structured_params['rule_json']
        summary = (
            f"**Name**: {rule_json.get('name', 'N/A')}. \n"
            f"**Description**: {rule_json.get('description', 'N/A')}. \n"
            f"**Action**: {rule_json.get('action', 'N/A')}. \n"
            f"**Trigger**: {rule_json.get('trigger', 'N/A')}"
        )
        
        # Get the payload for rule creation
        payload = structured_params.get('rule_map_json', {})
        
        # PREVIEW MODE - Show preview and ask for confirmation
        if request.preview_only:
            preview_msg = f"""**RULE PREVIEW**

                            Ready to create data protection rule:
                            {summary}
                            
                            Do you want to proceed? Reply **yes** to confirm or **no** to cancel.
                            """
            return CreateRuleResponse(
                success=True,
                message=preview_msg,
                preview_json=payload
            )
        
        # CREATE MODE - Actually create the rule
        result = await create_rule_from_payload(payload)
        
        # Build URL based on environment
        if settings.di_env_mode.upper() == ENV_MODE_SAAS:
            url_prefix = str(settings.di_service_url).replace("https://api.",
                                                              "https://") + "/governance/rules/dataProtection/view/"
        else:
            url_prefix = str(tool_helper_service.ui_base_url) + "/gov/rules/dataProtection/view/"
        
        # Handle successful creation
        if result["success"] and result["guid"]:
            rule_id = result["guid"]
            rule_url = url_prefix + rule_id
            success_message = f"\n✅ **Rule created successfully!**\n\n**Name**: {result['name']}. \n**View the rule**: {rule_url}"
            return CreateRuleResponse(
                success=True,
                message=success_message,
                rule_id=rule_id,
                url=rule_url
            )
        else:
            error_message = f"Data protection rule API returned success but missing expected metadata, response: {result['response']}"
            return CreateRuleResponse(
                success=False,
                message=error_message,
                error=error_message
            )
    
    except ExternalAPIError as e:
        error_msg = f"Failed to create rule due to external API error: {str(e)}"
        LOGGER.error(error_msg)
        return CreateRuleResponse(
            success=False,
            message=error_msg,
            error=str(e)
        )
    except Exception as e:
        error_msg = f"Failed in rule creation: {type(e).__name__}: {str(e)}"
        LOGGER.error(error_msg)
        return CreateRuleResponse(
            success=False,
            message=error_msg,
            error=f"{type(e).__name__}: {str(e)}"
        )

@service_registry.tool(
    name="create_data_protection_rule",
    description=RULE_CREATION_DESCRIPTION,
    tags={"create", "data_protection_rules", "json", "wxo", "llm_integration"},
    meta={"version": "2.0", "service": "data_protection_rules"},
)
@auto_context
async def wxo_create_rule(
    rule_json: str,
    preview_only: bool = True
) -> CreateRuleResponse:
    """
    Watsonx Orchestrator compatible version for rule creation.

    This function expands CreateRuleRequest object into individual parameters.
    For direct API usage with request objects, use create_data_protection_rule instead.
    """
    
    request = CreateRuleRequest(
        rule_json=rule_json,
        preview_only=preview_only
    )
    
    # Call the natural language create function
    return await create_data_protection_rule(request)
