# Copyright [2025] [IBM]
# Licensed under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
# See the LICENSE file in the project root for license information.
# This file has been modified with the assistance of IBM Bob AI tool

import json
from typing import Dict, Any
from app.core.auth import get_access_token
from app.shared.utils.http_client import get_http_client
from app.services.constants import JSON_CONTENT_TYPE, DP_TRANSFORM
from app.core.settings import settings
from app.services.constants import DPR_RULES
from app.shared.logging import LOGGER
from app.shared.exceptions.base import ExternalAPIError, ServiceError
from app.shared.utils.tool_helper_service import tool_helper_service
# Constants
ASSET_INFERRED_CLASSIFICATION = "Asset.InferredClassification"
ASSET_TAGS = "Asset.Tags"
ASSET_NAME = "Asset.Name"
ASSET_OWNER = "Asset.Owner"

async def get_json_to_data_protect_rule(json_string: str) -> Dict[str, Any]:
    """
    Call dp-transform service to convert JSON rule to final rule format (SaaS only).
    
    IMPORTANT: The input should be a JSON string that has been generated by the LLM
    on the client side using the prompts:
    
    The client should:
    1. Load base_prompt and examples using prompt_loader.prepare_rule_generation_prompt()
    2. Use LLM to convert natural language to JSON string
    3. Pass the JSON string to this function

    Args:
        json_string (str): JSON string representation of the rule (generated by client-side LLM)

    Returns:
       dict: include rule json in the dict with status and validation results
    """
    # Validate that input is valid JSON
    try:
        rule_dict = json.loads(json_string)
        LOGGER.info(f"Validated JSON input for rule: {rule_dict.get('name', 'Unknown')}")
    except json.JSONDecodeError as e:
        error_msg = f"Invalid JSON input: {str(e)}"
        LOGGER.error(error_msg)
        return {
            "rule_json": {},
            "status": "error",
            "rule_map_json": {},
            "message": f"{error_msg}. The input must be a valid JSON string generated by the LLM using the provided prompts."
        }
    
    token = await get_access_token()
    headers = {
        "Content-Type": JSON_CONTENT_TYPE,
        "Authorization": token,
    }
    client = get_http_client()

    # Send JSON string to json_to_rule endpoint
    # CRITICAL: The API expects {"json": "<json_string>"} where the value is a STRING, not an object
    # We must ensure json_string remains a string in the final payload
    payload = {"json": json_string}

    try:
        response = await tool_helper_service.execute_post_request(
            url=f"{tool_helper_service.base_url}{DP_TRANSFORM}/json_to_rule",
            json=payload,
            tool_name="create_json_data_protect_rule"
        )

        return {
            "rule_json": response.get("rule_json", {}),
            "status": response.get("status", {}),
            "rule_map_json": response.get("rule_map_json", {}),
            "message": response.get("message", {})
        }
    except ExternalAPIError as e:
        LOGGER.error(f"Failed to call dp-transform service: {str(e)}")
        raise ExternalAPIError(f"Failed to convert JSON to data protection rule: {str(e)}")
    except Exception as e:
        LOGGER.error(f"Unexpected error calling dp-transform service: {str(e)}")
        raise ServiceError(f"Failed to convert JSON to data protection rule: {str(e)}")

async def create_rule_from_payload(payload: Dict) -> Dict:
    """Create the actual rule via API.
    
    Returns:
        Dict with keys: success (bool), guid (str), name (str), response (dict)
    """
    token = await get_access_token()
    headers = {
        "Content-Type": JSON_CONTENT_TYPE,
        "Authorization": token,
    }
    client = get_http_client()

    response = await tool_helper_service.execute_post_request(
        url=f"{tool_helper_service.base_url}{DPR_RULES}",
        json=payload,
        tool_name="create_data_protect_rule"
    )

    # For successful creation (201)
    if response.get("metadata", {}).get("guid"):
        guid = response["metadata"]["guid"]
        return {
            "success": True,
            "guid": guid,
            "name": payload.get('name', 'N/A'),
            "response": response
        }
    else:
        return {
            "success": False,
            "guid": None,
            "name": payload.get('name', 'N/A'),
            "response": response
        }


